### ISSUE TITLE
Windows Hyper-V support

### ISSUE THREAD

**Issue by carlin-q-scott** [cmiles74/docker-vscode#1]
I got this working on Windows using xming and the xterm opens fine and I can Firefox and emacs, but when I run /developer/bin/start-vscode it immediately returns with no indication of what failed.

I'm using the following command to run the docker container:
`docker run -it --rm --name vscode -e DISPLAY=10.0.75.1:0.0 -e SHELL=/bin/bash -p 5000:5000 --entrypoint "xterm" -v %USERPROFILE%\.vscode:/developer/.vscode -v %CD%:/developer/project -v %USERPROFILE%\.ssh:/developer/.ssh -v %USERPROFILE%\.gitconfig:/developer/.gitconfig cmiles74/docker-vscode`

**Comment by cmiles74** [comment]
Visual Studio Code will fail silently if it has a problem, it won't spit out any useful output. If you switch to the xterm window and type `code --verbose` you'll see a lot more detail and hopefully something that will hint at the issue.

I just pulled down the current Docker image and ran it on my Linux machine and it does run... I am curious to know what Code thinks is missing. `:-)`
