### ISSUE TITLE
Issues with /dev/snd

### ISSUE THREAD

**Issue by NevilleBulmer** [cmiles74/docker-vscode#3]
I was wondering if you could help, I can pull the images perfectly fine but when I attempt to run it i get 

docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/snd": no such file or directory.

I'm unsure what I am doing wrong, any help would be appreciated.

**Comment by cmiles74** [comment]
The run script that comes packaged with the project tries to map in the device /dev/snd...

```
  docker run -d \
      -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
      -v ${PWD}/project:/project \
      -v $XAUTHORITY:/developer/.Xauthority \
      -e DISPLAY=unix${DISPLAY} \
      -e XAUTHORITY=/developer/.Xauthority \
      -p 5000:5000 \
      --device /dev/snd \
      --name docker-vscode \
      --entrypoint "urxvt" \
      cmiles74/docker-vscode
```

I think you want to just delete that line. It could be you don't have a sound device or it might be called something else. In either case, removing `--device /dev/snd` from the script should get things working. `:-)`

**Comment by NevilleBulmer** [comment]
One more question, am I able to use this approach from an ubuntu VPS or would this only work locally, thank you for the reply too. :-)

**Comment by cmiles74** [comment]
I think that if you have an X session on the VPS and you can run other GUI apps like a web browser then the image should work okay. That's something I haven't ever tested, though.
